import type { ElementNode } from "./types";

export const defaultAnimation = {
  type: "none",
  trigger: "page-load",
  duration: 0.8,
  delay: 0,
  ease: "power3.out",
  stagger: 0,
} as const;

export const defaultTree: ElementNode = {
  id: "hero-section",
  type: "section",
  name: "section",
  props: {},
  styles: {
    desktop: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
      width: "full",
      padding: "px-10 py-16 min-h-screen",
      margin: "m-0",
      gap: "gap-0",
      borderRadius: "rounded-none",
      background: "bg-slate-950",
      textColor: "text-white",
      opacity: 1,
      zIndex: 0,
      overflow: "hidden",
    },
    mobile: {
      padding: "px-5 py-10 min-h-screen",
    },
    tablet: {
      padding: "px-8 py-12 min-h-screen",
    },
  },
  animation: { ...defaultAnimation },
  children: [
    {
      id: "hero-container",
      type: "div",
      name: "container div",
      props: {},
      styles: {
        desktop: {
          display: "grid",
          justifyContent: "center",
          alignItems: "center",
          position: "relative",
          width: "full",
          maxWidth: "max-w-[1120px]",
          padding: "p-6",
          margin: "mx-auto",
          gap: "gap-8",
          borderRadius: "rounded-2xl",
          background: "bg-white/10",
          textColor: "text-white",
          opacity: 1,
          zIndex: 10,
          overflow: "hidden",
        },
        mobile: {
          display: "flex",
          flexDirection: "column",
          padding: "p-4",
          gap: "gap-6",
          width: "full",
        },
        tablet: {
          display: "flex",
          flexDirection: "column",
          maxWidth: "max-w-3xl",
          padding: "p-6",
          gap: "gap-8",
        },
      },
      animation: { ...defaultAnimation, type: "fade-in" },
      children: [
        {
          id: "text-column",
          type: "div",
          name: "left text column",
          props: {},
          styles: {
            desktop: {
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "start",
              width: "full",
              gap: "gap-5",
              padding: "p-2",
              margin: "m-0",
              borderRadius: "rounded-2xl",
              background: "bg-transparent",
              textColor: "text-white",
              opacity: 1,
              overflow: "visible",
            },
            mobile: {
              alignItems: "center",
              gap: "gap-4",
              padding: "p-0",
            },
          },
          animation: { ...defaultAnimation, type: "slide-up", stagger: 0.08 },
          children: [
            {
              id: "hero-heading",
              type: "heading",
              name: "heading",
              props: { text: "Build animated sections visually" },
              styles: {
                desktop: {
                  display: "block",
                  width: "full",
                  padding: "p-0",
                  margin: "m-0",
                  fontSize: "text-5xl",
                  fontWeight: "font-bold",
                  lineHeight: "leading-tight",
                  textColor: "text-white",
                  background: "bg-transparent",
                  customClassName: "max-w-3xl",
                  opacity: 1,
                  overflow: "visible",
                },
                mobile: { fontSize: "text-3xl", textColor: "text-white", textAlign: "center" },
                tablet: { fontSize: "text-4xl", textColor: "text-white", textAlign: "center" },
              },
              animation: { ...defaultAnimation, type: "slide-up", delay: 0.1 },
              children: [],
            },
            {
              id: "hero-paragraph",
              type: "paragraph",
              name: "paragraph",
              props: { text: "Design responsive React, Tailwind, and GSAP sections without losing control of the code." },
              styles: {
                desktop: {
                  display: "block",
                  width: "full",
                  padding: "p-0",
                  margin: "m-0",
                  fontSize: "text-lg",
                  fontWeight: "font-normal",
                  lineHeight: "leading-relaxed",
                  textColor: "text-slate-300",
                  background: "bg-transparent",
                  customClassName: "max-w-xl",
                  opacity: 1,
                  overflow: "visible",
                },
                mobile: { fontSize: "text-base", textColor: "text-slate-300", textAlign: "center" },
              },
              animation: { ...defaultAnimation, type: "slide-up", delay: 0.2 },
              children: [],
            },
            {
              id: "hero-button",
              type: "button",
              name: "button",
              props: { text: "Get Started" },
              styles: {
                desktop: {
                  display: "block",
                  width: "fit",
                  padding: "px-5 py-3",
                  margin: "m-0",
                  borderRadius: "rounded-full",
                  fontSize: "text-base",
                  fontWeight: "font-semibold",
                  textColor: "text-slate-950",
                  background: "bg-cyan-300",
                  opacity: 1,
                  overflow: "visible",
                },
              },
              animation: { ...defaultAnimation, type: "scale-in", delay: 0.3 },
              children: [],
            },
          ],
        },
        {
          id: "visual-card",
          type: "image",
          name: "image placeholder / visual block",
          props: { alt: "Animated section preview card" },
          styles: {
            desktop: {
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              width: "full",
              maxWidth: "max-w-[520px]",
              height: "280px",
              aspectRatio: "aspect-video",
              padding: "p-6",
              margin: "m-0",
              gap: "gap-4",
              borderRadius: "rounded-3xl",
              background: "bg-gradient-to-br from-cyan-300 via-blue-400 to-violet-500",
              textColor: "text-white",
              opacity: 1,
              overflow: "hidden",
            },
            mobile: { maxWidth: "max-w-full", height: "220px", padding: "p-5" },
            tablet: { maxWidth: "max-w-xl", height: "260px", padding: "p-6" },
          },
          animation: { ...defaultAnimation, type: "slide-left", delay: 0.15 },
          children: [],
        },
      ],
    },
  ],
};
